# Generated by Django 4.0 on 2022-01-08 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Joined',
            new_name='joined',
        ),
    ]
