# Generated by Django 4.0 on 2022-01-08 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField(default='', max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=50)),
                ('avatar', models.ImageField(default='avatar.png', upload_to='avatars/')),
                ('bank', models.CharField(default='Equity Bank Ke', max_length=25)),
                ('salary', models.CharField(default='00.00', max_length=16)),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('Joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
